filtersets:
  filter-set-list:
    0:
      grades: C,D,E,HR
      employment-length-over: 3
      inquiries-under: 0
      payment-income-ratio-under: 0.10
      loan-count-over: 0
    1:
      grades: C,D,E,HR
      employment-length-over: 2
      inquiries-under: 0
      payment-income-ratio-under: 0.11
      loan-count-over: 4
    2:
      grades: B,C,D,E
      employment-length-over: 0
      inquiries-under: 1
      payment-income-ratio-under: 0.12
      loan-count-over: 8
    3:
      grades: AA,A,B,C,D,E
      employment-length-over: 0
      inquiries-under: 2
      payment-income-ratio-under: 0.13
      loan-count-over: 12